apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: web-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>GitOps Demo</title></head>
    <body style="background-color: #2d3436; color: white; text-align: center; padding-top: 50px;">
      <h1>Hello Eyal!!! </h1>
      <p>Deployed via ArgoCD</p>
    </body>
    </html>
